# Path to oh-my-zsh installation
export ZSH="$HOME/.oh-my-zsh"

# Theme
ZSH_THEME="agnoster"

# Plugins
plugins=(git)

source $ZSH/oh-my-zsh.sh

# History
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt SHARE_HISTORY
setopt APPEND_HISTORY

# Options
setopt AUTO_CD
setopt CORRECT

# Keybindings
bindkey -e

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -lah'

# Logo al abrir terminal
if [[ -o interactive ]] && command -v fastfetch >/dev/null; then
    fastfetch
fi
export PATH="$HOME/.local/bin:$PATH"
